### ISSUE TITLE
EACCES: permission denied, open '/index.html'

### ISSUE THREAD

**Issue by dinvlad** [marcules/karma-remap-istanbul#25]
I'm trying to use this plugin according to the example on karma-coverage, however after the coverage is created successfully (but not remapped yet), the plugin throws this error:

```
{ [Error: EACCES: permission denied, open '/index.html']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/index.html' }
Error: EACCES: permission denied, open '/index.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at SyncFileWriter.extend.writeFile (/home/ubuntu/workspace/node_modules/karma-remap-istanbul/node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:58:12)
    at FileWriter.extend.writeFile (/home/ubuntu/workspace/node_modules/karma-remap-istanbul/node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at HtmlReport.Report.mix.writeFiles (/home/ubuntu/workspace/node_modules/karma-remap-istanbul/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:479:16)
    at /home/ubuntu/workspace/node_modules/karma-remap-istanbul/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:484:22
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/home/ubuntu/workspace/node_modules/karma-remap-istanbul/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:482:23)
    at HtmlReport.Report.mix.writeReport (/home/ubuntu/workspace/node_modules/karma-remap-istanbul/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:566:14)
    at /home/ubuntu/workspace/node_modules/karma-remap-istanbul/node_modules/remap-istanbul/lib/writeReport.js:77:22
    at /home/ubuntu/workspace/node_modules/karma-remap-istanbul/node_modules/remap-istanbul/node_modules/amdefine/amdefine.js:125:34
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

It seems to want to open the default browser, which is not possible as I'm developing in a cloud IDE (Cloud9). Is it possible to turn this feature off?

Thanks

**Comment by dinvlad** [comment]
If it helps, when I try to 'open' a file through command line, it says
`Couldn't get a file descriptor referring to the console`.

I'm not sure if it's a limitation of the cloud environment (running in a Docker container), but I haven't seen this error with any other plugins.

**Comment by dinvlad** [comment]
This issue may be related to the upstream when using Webpack (as in my case): https://github.com/SitePen/remap-istanbul/issues/68
