### ISSUE TITLE
Latest release causes build issues

### ISSUE THREAD

**Issue by remojansen** [marcules/karma-remap-istanbul#31]
I have a[ PR to update to the latest version](https://github.com/redux-bootstrap/redux-bootstrap-example/pull/9) in one of my projects. The build is broken:

```
20 12 2016 11:06:05.071:ERROR [karma]: Error: No element indexed by 1
    at ArraySet_at [as at] (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/source-map/lib/array-set.js:92:9)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/source-map/lib/source-map-consumer.js:619:34)
    at getMapping (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/getMapping.js:27:26)
    at getMappingResolved (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/CoverageTransformer.js:204:46)
    at remapBranch (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/remapBranch.js:14:19)
    at /home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/CoverageTransformer.js:214:44
    at Array.forEach (native)
    at CoverageTransformer.addFileCoverage (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/CoverageTransformer.js:210:42)
    at /home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/CoverageTransformer.js:268:14
    at Array.forEach (native)
    at CoverageTransformer.addCoverage (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/CoverageTransformer.js:266:24)
    at /home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/remap.js:48:13
    at Array.forEach (native)
    at remap (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/remap-istanbul/lib/remap.js:47:16)
    at KarmaRemapIstanbul.onRunComplete (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/karma-remap-istanbul/index.js:58:21)
    at Server.<anonymous> (/home/travis/build/redux-bootstrap/redux-bootstrap-example/node_modules/karma/lib/events.js:13:22)
```

You can see a full error log at https://travis-ci.org/redux-bootstrap/redux-bootstrap-example/builds/185394142

Thanks!

**Comment by mattlewis92** [comment]
I can reproduce, I think the issue is caused by the remap istanbul upgrade in 0.3.0 as that's where the error is coming from. I will see if there's an easy fix and worst case downgrade remap-istanbul to a lower, working version until the issue is resolved upstream :smile:

**Comment by remojansen** [comment]
Thanks for working on a fix :smile:

**Comment by mattlewis92** [comment]
@remojansen I've downgraded remap-istanbul to 0.6.x and cut a 0.4.0 release with that which should resolve your issues in the meantime. I will dig a big deeper when I have some more time and try and see if I can figure out what the issue is that broke your specific project.

**Comment by remojansen** [comment]
Thanks a lot. 0.4.0 is working for me 👍

**Comment by remojansen** [comment]
Should I close this issue or leave it open for your investigation?

**Comment by mattlewis92** [comment]
Please leave it open for now as I'd like to dig into why this is happening, get it fixed and then upgrade remap-istanbul again :)

**Comment by mattlewis92** [comment]
Spent far longer trying to fix this than I would have liked, had to settle on a PR to the project to fix the issue there directly: https://github.com/redux-bootstrap/redux-bootstrap-example/pull/10

**Comment by mattlewis92** [comment]
Further digging revealed that this was the commit in remap-istanbul that broke the project: https://github.com/SitePen/remap-istanbul/pull/65

**Comment by mattlewis92** [comment]
PR sent that resolves the issue: https://github.com/SitePen/remap-istanbul/pull/120
