### ISSUE TITLE
Why don't work your example with webpack on Windows PC?

### ISSUE THREAD

**Issue by sotnikov-link** [marcules/karma-remap-istanbul#41]
I'm receiving blank reports when I use `npm run test` on Windows PC:

![image](https://user-images.githubusercontent.com/10273334/27252366-4fe75c2a-5365-11e7-99cd-ce62a4c74f4b.png)

***

But `npm run test` work on MacOS:

![image](https://user-images.githubusercontent.com/10273334/27252608-904475c2-536b-11e7-8719-a2459bee64ed.png)

***

This problem was discovered in [my boilerplate](https://github.com/sotnikov-link/ts-react-boilerplate) which uses your karma-config.

I ran script for tests on different PC: Win7, Win10, Node.js 6, Node.js 8, npm 3, npm 5. Results were same.

***

# Logs

### MacOS
```text
> karma-remap-istanbul-example@1.0.0 test /Users/Valeriy/Projects/_github/karma-remap-istanbul/examples/webpack
> karma start

Hash: e0bdc8cc97632b01d813
Version: webpack 2.6.1
Time: 46ms
webpack: Compiled successfully.
webpack: Compiling...
ts-loader: Using typescript@2.3.4 and /Users/Valeriy/Projects/_github/karma-remap-istanbul/examples/webpack/tsconfig.json
Hash: 43bf9646bfb07d28c8ce
Version: webpack 2.6.1
Time: 1322ms
            Asset    Size  Chunks                    Chunk Names
test/test.spec.ts  593 kB       0  [emitted]  [big]  test/test.spec.ts
chunk    {0} test/test.spec.ts (test/test.spec.ts) 214 kB [entry] [rendered]
    [0] ./~/chai/lib/chai/utils/flag.js 807 bytes {0} [built]
    [1] ./~/chai/lib/chai/config.js 1.46 kB {0} [built]
    [4] ./~/assertion-error/index.js 2.44 kB {0} [built]
   [11] ./~/chai/index.js 40 bytes {0} [built]
   [12] ./src/example.ts 3.78 kB {0} [built]
   [15] ./~/chai/lib/chai.js 1.28 kB {0} [built]
   [16] ./~/chai/lib/chai/assertion.js 3.79 kB {0} [built]
   [17] ./~/chai/lib/chai/core/assertions.js 51.8 kB {0} [built]
   [18] ./~/chai/lib/chai/interface/assert.js 40.9 kB {0} [built]
   [19] ./~/chai/lib/chai/interface/expect.js 770 bytes {0} [built]
   [20] ./~/chai/lib/chai/interface/should.js 5.67 kB {0} [built]
   [21] ./~/chai/lib/chai/utils/addChainableMethod.js 3.63 kB {0} [built]
   [29] ./~/chai/lib/chai/utils/index.js 1.71 kB {0} [built]
   [34] ./~/deep-eql/index.js 39 bytes {0} [built]
   [40] ./test/test.spec.ts 353 bytes {0} [built]
     + 28 hidden modules
webpack: Compiled successfully.
[32m17 06 2017 14:42:15.011:INFO [karma]: [39mKarma v1.7.0 server started at http://0.0.0.0:9876/
[32m17 06 2017 14:42:15.013:INFO [launcher]: [39mLaunching browser PhantomJS with unlimited concurrency
[32m17 06 2017 14:42:15.031:INFO [launcher]: [39mStarting browser PhantomJS
[32m17 06 2017 14:42:16.241:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: [39mConnected on socket 3QXq5mtuX9Q4THzMAAAA with id 26235617
.
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 SUCCESS (0.007 secs / 0.001 secs)

=============================== Coverage summary ===============================
Statements   : 85.71% ( 6/7 )
Branches     : 100% ( 0/0 )
Functions    : 66.67% ( 2/3 )
Lines        : 83.33% ( 5/6 )
================================================================================

```

### Windows
```
> karma-remap-istanbul-example@1.0.0 test D:\Projects\karma-remap-istanbul\examples\webpack
> karma start

Hash: e0bdc8cc97632b01d813
Version: webpack 2.6.1
Time: 78ms
webpack: Compiled successfully.
webpack: Compiling...
ts-loader: Using typescript@2.3.4 and D:\Projects\karma-remap-istanbul\examples\webpack\tsconfig.json
Hash: 009e53f1133f50e50e20
Version: webpack 2.6.1
Time: 2530ms
            Asset    Size  Chunks                    Chunk Names
test/test.spec.ts  583 kB       0  [emitted]  [big]  test/test.spec.ts
chunk    {0} test/test.spec.ts (test/test.spec.ts) 211 kB [entry] [rendered]
    [0] ./~/chai/lib/chai/utils/flag.js 807 bytes {0} [built]
    [1] ./~/chai/lib/chai/config.js 1.46 kB {0} [built]
    [4] ./~/assertion-error/index.js 2.44 kB {0} [built]
   [11] ./~/chai/index.js 40 bytes {0} [built]
   [12] ./src/example.ts 342 bytes {0} [built]
   [15] ./~/chai/lib/chai.js 1.28 kB {0} [built]
   [16] ./~/chai/lib/chai/assertion.js 3.79 kB {0} [built]
   [17] ./~/chai/lib/chai/core/assertions.js 51.8 kB {0} [built]
   [18] ./~/chai/lib/chai/interface/assert.js 40.9 kB {0} [built]
   [19] ./~/chai/lib/chai/interface/expect.js 770 bytes {0} [built]
   [20] ./~/chai/lib/chai/interface/should.js 5.67 kB {0} [built]
   [21] ./~/chai/lib/chai/utils/addChainableMethod.js 3.63 kB {0} [built]
   [29] ./~/chai/lib/chai/utils/index.js 1.71 kB {0} [built]
   [34] ./~/deep-eql/index.js 39 bytes {0} [built]
   [40] ./test/test.spec.ts 364 bytes {0} [built]
     + 28 hidden modules
webpack: Compiled successfully.
[32m17 06 2017 14:38:55.191:INFO [karma]: [39mKarma v1.7.0 server started at http://0.0.0.0:9876/
[32m17 06 2017 14:38:55.195:INFO [launcher]: [39mLaunching browser PhantomJS with unlimited concurrency
[32m17 06 2017 14:38:55.227:INFO [launcher]: [39mStarting browser PhantomJS
[32m17 06 2017 14:38:58.530:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: [39mConnected on socket uXQWAG8l6wfcZUdPAAAA with id 44955151
.
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 1 of 1 SUCCESS (0.012 secs / 0.003 secs)

=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
```

### MacOS
```
> karma-remap-istanbul@0.6.0 pretest /Users/Valeriy/Projects/_github/karma-remap-istanbul
> npm run lint


> karma-remap-istanbul@0.6.0 lint /Users/Valeriy/Projects/_github/karma-remap-istanbul
> xo


> karma-remap-istanbul@0.6.0 test /Users/Valeriy/Projects/_github/karma-remap-istanbul
> nyc mocha



  karma-remap-istanbul
    ✓ should generate a remapped coverage report (3649ms)
    ✓ should allow files to be excluded (2644ms)


  2 passing (6s)


=============================== Coverage summary ===============================
Statements   : 91.49% ( 43/47 )
Branches     : 75% ( 12/16 )
Functions    : 75% ( 9/12 )
Lines        : 91.49% ( 43/47 )
================================================================================
```

### Windows

```
> karma-remap-istanbul@0.6.0 pretest D:\Projects\karma-remap-istanbul
> npm run lint


> karma-remap-istanbul@0.6.0 lint D:\Projects\karma-remap-istanbul
> xo


> karma-remap-istanbul@0.6.0 test D:\Projects\karma-remap-istanbul
> nyc mocha



  karma-remap-istanbul
    1) should generate a remapped coverage report
    2) should allow files to be excluded


  0 passing (8s)
  2 failing

  1) karma-remap-istanbul should generate a remapped coverage report:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) karma-remap-istanbul should allow files to be excluded:

      Uncaught AssertionError: expected { Object (lines, statements, ...) } to deeply equal { Object (lines, statements, ...) }
      + expected - actual

           "skipped": 0
           "total": 0
         }
         "functions": {
      -    "covered": 0
      -    "pct": 100
      +    "covered": 2
      +    "pct": 66.67
           "skipped": 0
      -    "total": 0
      +    "total": 3
         }
         "lines": {
      -    "covered": 0
      -    "pct": 100
      +    "covered": 5
      +    "pct": 83.33
           "skipped": 0
      -    "total": 0
      +    "total": 6
         }
      -  "linesCovered": {}
      +  "linesCovered": {
      +    "1": 2
      +    "3": 1
      +    "4": 1
      +    "7": 1
      +    "8": 0
      +    "11": 1
      +  }
         "statements": {
      -    "covered": 0
      -    "pct": 100
      +    "covered": 6
      +    "pct": 85.71
           "skipped": 0
      -    "total": 0
      +    "total": 7
         }
       }
      
      at Assertion.assertEqual (node_modules\chai\lib\chai\core\assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules\chai\lib\chai\utils\addMethod.js:41:25)
      at Timeout.setTimeout [as _onTimeout] (test\index.spec.js:37:39)




=============================== Coverage summary ===============================
Statements   : 91.49% ( 43/47 )
Branches     : 68.75% ( 11/16 )
Functions    : 75% ( 9/12 )
Lines        : 91.49% ( 43/47 )
================================================================================
```

Do you have ideas how to solve this problem?

**Comment by sotnikov-link** [comment]
Easy solution: https://github.com/sotnikov-link/ts-react-boilerplate/commit/0068280fc555a2532972b57d863698720f82440f 🤣
