### ISSUE TITLE
Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by arobinson** [marcules/karma-remap-istanbul#49]
My lcov.info remapping worked just fine, but when I tried to include an HTML report, I got this error (paths shortened for readability):

```
ERROR [reporter.remap-istanbul]: [39mTypeError: Cannot read properties of null (reading 'split')
    at HtmlReport.writeDetailPage (.../istanbul@0.4.5/node_modules/istanbul/lib/report/html.js:412:31)
    at .../istanbul@0.4.5/node_modules/istanbul/lib/report/html.js:489:26
```

Not sure if the error is in istanbul or in this library due to some configuration with istanbul though

**Comment by arobinson** [comment]
Error was in this line:
```
code = sourceText.split(/(?:\r?\n)|\r/),
```
